<?xml version="1.0" encoding="utf-8"?><Database Name="QL_Tour" Class="QuanLyTourDuLichDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-86N3SME\SQL_KING;Initial Catalog=QL_Tour;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_TourConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DanhGia" Member="DanhGias">
    <Type Name="DanhGia">
      <Column Name="DanhGia_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tour_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="KhachHang_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="Noidung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Vote" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhachHang_DanhGia" Member="KhachHang" ThisKey="KhachHang_id" OtherKey="KhachHang_id" Type="KhachHang" IsForeignKey="true" />
      <Association Name="Tour_DanhGia" Member="Tour" ThisKey="Tour_id" OtherKey="Tour_id" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhToan" Member="ThanhToans">
    <Type Name="ThanhToan">
      <Column Name="ThanhToan_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DatTour_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayThanhToan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HinhThuc_id" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Association Name="DatTour_ThanhToan" Member="DatTour" ThisKey="DatTour_id" OtherKey="DatTour_id" Type="DatTour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatTour" Member="DatTours">
    <Type Name="DatTour">
      <Column Name="DatTour_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="KhachHang_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tour_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="SoNguoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DatTour_ThanhToan" Member="ThanhToans" ThisKey="DatTour_id" OtherKey="DatTour_id" Type="ThanhToan" />
      <Association Name="DatTour_HanhKhach" Member="HanhKhaches" ThisKey="DatTour_id" OtherKey="DatTour_id" Type="HanhKhach" />
      <Association Name="DatTour_HuyTour" Member="HuyTours" ThisKey="DatTour_id" OtherKey="DatTour_id" Type="HuyTour" />
      <Association Name="KhachHang_DatTour" Member="KhachHang" ThisKey="KhachHang_id" OtherKey="KhachHang_id" Type="KhachHang" IsForeignKey="true" />
      <Association Name="Tour_DatTour" Member="Tour" ThisKey="Tour_id" OtherKey="Tour_id" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HanhKhach" Member="HanhKhaches">
    <Type Name="HanhKhach">
      <Column Name="HanhKhach_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DatTour_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tour_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Association Name="DatTour_HanhKhach" Member="DatTour" ThisKey="DatTour_id" OtherKey="DatTour_id" Type="DatTour" IsForeignKey="true" />
      <Association Name="Tour_HanhKhach" Member="Tour" ThisKey="Tour_id" OtherKey="Tour_id" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HuyTour" Member="HuyTours">
    <Type Name="HuyTour">
      <Column Name="HuyTour_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DatTour_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayHuy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DatTour_HuyTour" Member="DatTour" ThisKey="DatTour_id" OtherKey="DatTour_id" Type="DatTour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Image_Tour" Member="Image_Tours">
    <Type Name="Image_Tour">
      <Column Name="Img_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Tour_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Association Name="Tour_Image_Tour" Member="Tour" ThisKey="Tour_id" OtherKey="Tour_id" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="KhachHang_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Gioitinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KhachHang_DanhGia" Member="DanhGias" ThisKey="KhachHang_id" OtherKey="KhachHang_id" Type="DanhGia" />
      <Association Name="KhachHang_DatTour" Member="DatTours" ThisKey="KhachHang_id" OtherKey="KhachHang_id" Type="DatTour" />
    </Type>
  </Table>
  <Table Name="dbo.KhachSan" Member="KhachSans">
    <Type Name="KhachSan">
      <Column Name="KhachSan_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TinhThanh_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tinhtrang" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="KhachSan_Tour" Member="Tours" ThisKey="KhachSan_id" OtherKey="KhachSan_id" Type="Tour" />
      <Association Name="TinhThanh_KhachSan" Member="TinhThanh" ThisKey="TinhThanh_id" OtherKey="TinhThanh_id" Type="TinhThanh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhaHang" Member="NhaHangs">
    <Type Name="NhaHang">
      <Column Name="NhaHang_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TinhThanh_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhaHang_NhaHang_Tour" Member="NhaHang_Tours" ThisKey="NhaHang_id" OtherKey="NhaHang_id" Type="NhaHang_Tour" />
      <Association Name="TinhThanh_NhaHang" Member="TinhThanh" ThisKey="TinhThanh_id" OtherKey="TinhThanh_id" Type="TinhThanh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhaHang_Tour" Member="NhaHang_Tours">
    <Type Name="NhaHang_Tour">
      <Column Name="NhaHang_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tour_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NhaHang_NhaHang_Tour" Member="NhaHang" ThisKey="NhaHang_id" OtherKey="NhaHang_id" Type="NhaHang" IsForeignKey="true" />
      <Association Name="Tour_NhaHang_Tour" Member="Tour" ThisKey="Tour_id" OtherKey="Tour_id" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="NhanVien_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_PhanCong_NhanVien" Member="PhanCong_NhanViens" ThisKey="NhanVien_id" OtherKey="NhanVien_id" Type="PhanCong_NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.PhanCong_NhanVien" Member="PhanCong_NhanViens">
    <Type Name="PhanCong_NhanVien">
      <Column Name="Tour_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NhanVien_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NhanVien_PhanCong_NhanVien" Member="NhanVien" ThisKey="NhanVien_id" OtherKey="NhanVien_id" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Tour_PhanCong_NhanVien" Member="Tour" ThisKey="Tour_id" OtherKey="Tour_id" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TinhThanh" Member="TinhThanhs">
    <Type Name="TinhThanh">
      <Column Name="TinhThanh_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="TinhThanh_KhachSan" Member="KhachSans" ThisKey="TinhThanh_id" OtherKey="TinhThanh_id" Type="KhachSan" />
      <Association Name="TinhThanh_NhaHang" Member="NhaHangs" ThisKey="TinhThanh_id" OtherKey="TinhThanh_id" Type="NhaHang" />
      <Association Name="TinhThanh_Tour" Member="Tours" ThisKey="TinhThanh_id" OtherKey="DiemDen_id" Type="Tour" />
      <Association Name="TinhThanh_Tour1" Member="Tours1" ThisKey="TinhThanh_id" OtherKey="DiemKhoiHanh_id" Type="Tour" />
    </Type>
  </Table>
  <Table Name="dbo.Tour" Member="Tours">
    <Type Name="Tour">
      <Column Name="Tour_id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LichTrinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiemKhoiHanh_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemDen_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KhachSan_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="NgayKhoiHanh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuongCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiTour" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Tour_DanhGia" Member="DanhGias" ThisKey="Tour_id" OtherKey="Tour_id" Type="DanhGia" />
      <Association Name="Tour_DatTour" Member="DatTours" ThisKey="Tour_id" OtherKey="Tour_id" Type="DatTour" />
      <Association Name="Tour_HanhKhach" Member="HanhKhaches" ThisKey="Tour_id" OtherKey="Tour_id" Type="HanhKhach" />
      <Association Name="Tour_Image_Tour" Member="Image_Tours" ThisKey="Tour_id" OtherKey="Tour_id" Type="Image_Tour" />
      <Association Name="Tour_NhaHang_Tour" Member="NhaHang_Tours" ThisKey="Tour_id" OtherKey="Tour_id" Type="NhaHang_Tour" />
      <Association Name="Tour_PhanCong_NhanVien" Member="PhanCong_NhanViens" ThisKey="Tour_id" OtherKey="Tour_id" Type="PhanCong_NhanVien" />
      <Association Name="TinhThanh_Tour" Member="TinhThanh" ThisKey="DiemDen_id" OtherKey="TinhThanh_id" Type="TinhThanh" IsForeignKey="true" />
      <Association Name="TinhThanh_Tour1" Member="TinhThanh1" ThisKey="DiemKhoiHanh_id" OtherKey="TinhThanh_id" Type="TinhThanh" IsForeignKey="true" />
      <Association Name="KhachSan_Tour" Member="KhachSan" ThisKey="KhachSan_id" OtherKey="KhachSan_id" Type="KhachSan" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.UpdateTour" Method="UpdateTour">
    <Parameter Name="Tour_id" Parameter="tour_id" Type="System.String" DbType="VarChar(36)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Gia" Parameter="gia" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="MoTa" Parameter="moTa" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="LichTrinh" Parameter="lichTrinh" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DiemKhoiHanh_id" Parameter="diemKhoiHanh_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="DiemDen_id" Parameter="diemDen_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="KhachSan_id" Parameter="khachSan_id" Type="System.String" DbType="VarChar(36)" />
    <Parameter Name="NgayKhoiHanh" Parameter="ngayKhoiHanh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NgayKetThuc" Parameter="ngayKetThuc" Type="System.DateTime" DbType="Date" />
    <Parameter Name="SoLuongCon" Parameter="soLuongCon" Type="System.Int32" DbType="Int" />
    <Parameter Name="LoaiTour" Parameter="loaiTour" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="TrangThai" Parameter="trangThai" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.proc_ThemMoiTour" Method="proc_ThemMoiTour">
    <Parameter Name="Tour_id" Parameter="tour_id" Type="System.String" DbType="VarChar(36)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Gia" Parameter="gia" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="MoTa" Parameter="moTa" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="LichTrinh" Parameter="lichTrinh" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DiemKhoiHanh_id" Parameter="diemKhoiHanh_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="DiemDen_id" Parameter="diemDen_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="KhachSan_id" Parameter="khachSan_id" Type="System.String" DbType="VarChar(36)" />
    <Parameter Name="NgayKhoiHanh" Parameter="ngayKhoiHanh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NgayKetThuc" Parameter="ngayKetThuc" Type="System.DateTime" DbType="Date" />
    <Parameter Name="SoLuongCon" Parameter="soLuongCon" Type="System.Int32" DbType="Int" />
    <Parameter Name="LoaiTour" Parameter="loaiTour" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="TrangThai" Parameter="trangThai" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_TimKiemTours" Method="sp_TimKiemTours">
    <Parameter Name="NgayKH" Parameter="ngayKH" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MucGia" Parameter="mucGia" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="NoiDen" Parameter="noiDen" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="LoaiTour" Parameter="loaiTour" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="sp_TimKiemToursResult">
      <Column Name="Tour_id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LichTrinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiemKhoiHanh_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemDen_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KhachSan_id" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="NgayKhoiHanh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuongCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiTour" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TinhThanh_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name1" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ThemNhaHang" Method="sp_ThemNhaHang">
    <Parameter Name="maTour" Type="System.String" DbType="VarChar(36)" />
    <Parameter Name="maNhaHang" Type="System.String" DbType="VarChar(36)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTourDetailsByDatTourId" Method="GetTourDetailsByDatTourId">
    <Parameter Name="DatTour_id" Parameter="datTour_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTourDetailsByDatTourIdResult">
      <Column Name="Tour_id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="TenTour" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DiemKhoiHanh" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DiemDen" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="NgayKhoiHanh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Phancong_nv" Method="Phancong_nv" IsComposable="true">
    <Parameter Name="Tour_id" Parameter="tour_id" Type="System.String" DbType="VarChar(36)" />
    <ElementType Name="Phancong_nvResult">
      <Column Name="NhanVien_id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SoLuongCon" Method="SoLuongCon" IsComposable="true">
    <Parameter Name="tourid" Type="System.String" DbType="VarChar(36)" />
    <Return Type="System.Int32" />
  </Function>
</Database>